import { ModelFCApiError } from "./errors";
import type { AnalysisRequest, AnalysisResponse, AnalyzedMarket, CapabilitiesResponse } from "./types";

export const mockCapabilities: CapabilitiesResponse = {
  api_version: "v1",
  stake: 1,
  models: ["venue-opponent-negative-binomial", "venue-opponent-poisson"],
  markets: ["TEAM_TOTAL", "MATCH_TOTAL"],
  competitions: [
    {
      code: "E1", name: "Championship", provider: "synthetic-history", analysis: true,
      automatic_refresh: false, automatic_settlement: "MANUAL_ONLY", trusted_kickoff_source: null,
      latest_result_date: "2026-09-14", last_refresh_at: null, stale: true,
      warnings: [{ code: "SYNTHETIC_DEMO_DATA", message: "Demo responses use a fixed fixture generated by the Python backend from synthetic history." }],
    },
    {
      code: "SP2", name: "La Liga 2", provider: "football-data", analysis: false,
      automatic_refresh: false, automatic_settlement: "MANUAL_ONLY", trusted_kickoff_source: null,
      latest_result_date: null, last_refresh_at: null, stale: true,
      warnings: [{ code: "COMPETITION_NOT_CONFIGURED", message: "La Liga 2 is recognized in pasted text, but backend data is not configured yet." }],
    },
  ],
};

const fixedMarkets: Record<string, Omit<AnalyzedMarket, "client_market_id">> = {
  "TEAM_TOTAL:HOME:OVER:4:-145": {
    market_type: "TEAM_TOTAL", team_side: "HOME", side: "OVER", line: 4, american_odds: -145,
    team: "Coventry City", status: "SUPPORTED", unsupported_reason: null,
    model_probability: 0.6807092378053914, push_probability: 0.13924546100166266,
    decisive_model_probability: 0.7908285195887956, implied_probability: 0.5918367346938775,
    probability_edge: 0.1989917848949181, expected_profit: 0.289409345569393,
    expected_corners: 5.8555648059780285,
    warnings: [
      { code: "TEAM_HISTORY_AGE", message: "Coventry City history is older than the configured freshness target." },
      { code: "TEAM_VENUE_HISTORY_AGE", message: "Coventry City home history is older than the configured freshness target." },
    ],
  },
  "TEAM_TOTAL:AWAY:OVER:3.5:-120": {
    market_type: "TEAM_TOTAL", team_side: "AWAY", side: "OVER", line: 3.5, american_odds: -120,
    team: "Birmingham City", status: "SUPPORTED", unsupported_reason: null,
    model_probability: 0.39609958306487136, push_probability: 0,
    decisive_model_probability: 0.39609958306487125, implied_probability: 0.5454545454545454,
    probability_edge: -0.14935496238967416, expected_profit: -0.27381743104773604,
    expected_corners: 3.200241727370725,
    warnings: [
      { code: "TEAM_HISTORY_AGE", message: "Birmingham City history is older than the configured freshness target." },
      { code: "TEAM_VENUE_HISTORY_AGE", message: "Birmingham City away history is older than the configured freshness target." },
    ],
  },
  "MATCH_TOTAL::UNDER:10:-125": {
    market_type: "MATCH_TOTAL", team_side: null, side: "UNDER", line: 10, american_odds: -125,
    team: null, status: "SUPPORTED", unsupported_reason: null,
    model_probability: 0.5805148027479127, push_probability: 0.11376981099659327,
    decisive_model_probability: 0.6550383974176269, implied_probability: 0.5555555555555556,
    probability_edge: 0.09948284186207135, expected_profit: 0.15869645594283527,
    expected_corners: 9.055806533348754,
    warnings: [
      { code: "TEAM_HISTORY_AGE", message: "Fixture team history is older than the configured freshness target." },
      { code: "TEAM_VENUE_HISTORY_AGE", message: "Fixture venue history is older than the configured freshness target." },
    ],
  },
};

function marketKey(market: AnalysisRequest["markets"][number]): string {
  return [market.market_type, market.team_side ?? "", market.side, market.line, market.american_odds].join(":");
}

export async function mockAnalyze(request: AnalysisRequest, signal?: AbortSignal): Promise<AnalysisResponse> {
  await new Promise<void>((resolve, reject) => {
    const timeout = setTimeout(resolve, 250);
    signal?.addEventListener("abort", () => {
      clearTimeout(timeout);
      reject(new DOMException("Aborted", "AbortError"));
    }, { once: true });
  });
  const isDemoFixture = request.fixture.competition === "E1"
    && request.fixture.date === "2026-09-20"
    && request.fixture.home_team === "Coventry City"
    && request.fixture.away_team === "Birmingham City";
  const markets = request.markets.map((market) => {
    const fixed = fixedMarkets[marketKey(market)];
    return fixed ? { ...fixed, client_market_id: market.client_market_id } : null;
  });
  if (!isDemoFixture || markets.some((market) => market === null)) {
    throw new ModelFCApiError(
      "Mock mode only returns the fixed Coventry City vs Birmingham City backend fixture. Connect the live API for other inputs.",
      "DEMO_FIXTURE_ONLY",
      false,
      422,
    );
  }
  return {
    analysis_id: "demo-analysis-backend-generated",
    forecast_id: "demo-forecast-backend-generated",
    created_at: "2026-09-17T00:00:00Z",
    pick_logging: { status: "DISABLED", reason: "UNTRUSTED_KICKOFF" },
    fixture: { ...request.fixture, kickoff_at: null },
    forecast: {
      model: request.model,
      model_version: "backend-synthetic-main-1a2e935",
      configuration: { min_history: 4, min_venue_history: 2, smoothing_matches: 5, dispersion: 49.818840579710134, match_total_method: "independent_discrete_convolution" },
      home_expected_corners: 5.8555648059780285,
      away_expected_corners: 3.200241727370725,
      match_expected_corners: 9.055806533348754,
      latest_history_date: "2026-09-14",
      source_data_hashes: [{ filename: "synthetic-history.csv", sha256: "a0584f00f012960a9f24d856218275b823835f505e79cd3510476444b7405b37" }],
    },
    markets: markets as AnalyzedMarket[],
    warnings: [
      { code: "STALE_DATA", message: "Latest history is 6 days before the fixture." },
      { code: "UNTRUSTED_KICKOFF", message: "No trusted kickoff registry entry is available, so pick logging is disabled." },
    ],
  };
}
